#!/usr/bin/env python3
"""Verben mit Präposition - verb rection with governed case, A2 through B2.

Hand-curated. Format: verb, preposition, case (A = Akkusativ, D = Dativ),
English, example. Reflexive verbs are listed with 'sich'.
"""
import json

# verb, prep, case, english, example
DATA = [
    ("abhängen", "von", "D", "to depend on", "Das hängt vom Wetter ab."),
    ("achten", "auf", "A", "to pay attention to", "Achte auf die Verkehrsschilder!"),
    ("anfangen", "mit", "D", "to begin with", "Wir fangen mit der Übung an."),
    ("ankommen", "auf", "A", "to depend on", "Es kommt auf den Preis an."),
    ("antworten", "auf", "A", "to answer (sth)", "Er antwortet auf meine Frage."),
    ("arbeiten", "an", "D", "to work on", "Ich arbeite an einem Projekt."),
    ("sich ärgern", "über", "A", "to be annoyed about", "Ich ärgere mich über den Lärm."),
    ("aufhören", "mit", "D", "to stop doing", "Hör mit dem Rauchen auf!"),
    ("aufpassen", "auf", "A", "to look after", "Passt du auf die Kinder auf?"),
    ("sich aufregen", "über", "A", "to get worked up about", "Reg dich nicht über ihn auf!"),
    ("ausgeben", "für", "A", "to spend (money) on", "Ich gebe viel Geld für Bücher aus."),
    ("sich bedanken", "bei", "D", "to thank sb", "Ich bedanke mich bei Ihnen."),
    ("sich bedanken", "für", "A", "to give thanks for", "Er bedankt sich für das Geschenk."),
    ("beginnen", "mit", "D", "to begin with", "Wir beginnen mit dem Kapitel."),
    ("beitragen", "zu", "D", "to contribute to", "Das trägt zum Erfolg bei."),
    ("sich beklagen", "über", "A", "to complain about", "Sie beklagt sich über die Arbeit."),
    ("sich bemühen", "um", "A", "to make an effort for", "Er bemüht sich um eine Stelle."),
    ("berichten", "über", "A", "to report on", "Die Zeitung berichtet über den Unfall."),
    ("berichten", "von", "D", "to tell about", "Sie berichtet von ihrer Reise."),
    ("sich beschäftigen", "mit", "D", "to occupy oneself with", "Ich beschäftige mich mit Chemie."),
    ("sich beschweren", "über", "A", "to complain about", "Er beschwert sich über den Service."),
    ("sich beschweren", "bei", "D", "to complain to sb", "Sie beschwert sich beim Chef."),
    ("bestehen", "aus", "D", "to consist of", "Das Team besteht aus fünf Personen."),
    ("bestehen", "auf", "D", "to insist on", "Er besteht auf seinem Recht."),
    ("sich beteiligen", "an", "D", "to participate in", "Ich beteilige mich an der Diskussion."),
    ("sich bewerben", "um", "A", "to apply for", "Ich bewerbe mich um ein Praktikum."),
    ("sich bewerben", "bei", "D", "to apply to (company)", "Er bewirbt sich bei BASF."),
    ("bitten", "um", "A", "to ask for", "Ich bitte um Hilfe."),
    ("danken", "für", "A", "to thank for", "Ich danke dir für alles."),
    ("denken", "an", "A", "to think of", "Ich denke oft an dich."),
    ("denken", "über", "A", "to have an opinion about", "Was denkst du über den Plan?"),
    ("diskutieren", "über", "A", "to discuss", "Wir diskutieren über die Politik."),
    ("sich eignen", "für", "A", "to be suitable for", "Das Material eignet sich für Rohre."),
    ("einladen", "zu", "D", "to invite to", "Ich lade dich zum Essen ein."),
    ("sich entscheiden", "für", "A", "to decide on", "Ich entscheide mich für Option B."),
    ("sich entschließen", "zu", "D", "to resolve to", "Er entschließt sich zu einem Umzug."),
    ("sich entschuldigen", "bei", "D", "to apologise to", "Ich entschuldige mich bei dir."),
    ("sich entschuldigen", "für", "A", "to apologise for", "Er entschuldigt sich für die Verspätung."),
    ("sich erinnern", "an", "A", "to remember", "Ich erinnere mich an den Tag."),
    ("erkennen", "an", "D", "to recognise by", "Ich erkenne ihn an der Stimme."),
    ("sich erkundigen", "nach", "D", "to enquire about", "Sie erkundigt sich nach dem Preis."),
    ("erzählen", "von", "D", "to tell about", "Er erzählt von seinem Urlaub."),
    ("erzählen", "über", "A", "to tell about", "Sie erzählt über ihre Arbeit."),
    ("fragen", "nach", "D", "to ask for/about", "Er fragt nach dem Weg."),
    ("sich freuen", "auf", "A", "to look forward to", "Ich freue mich auf das Wochenende."),
    ("sich freuen", "über", "A", "to be glad about", "Ich freue mich über dein Geschenk."),
    ("führen", "zu", "D", "to lead to", "Das führt zu Problemen."),
    ("sich fürchten", "vor", "D", "to be afraid of", "Sie fürchtet sich vor Spinnen."),
    ("gehören", "zu", "D", "to belong to / be part of", "Er gehört zu unserem Team."),
    ("gelten", "als", "-", "to be regarded as", "Er gilt als Experte."),
    ("sich gewöhnen", "an", "A", "to get used to", "Ich gewöhne mich an das Klima."),
    ("glauben", "an", "A", "to believe in", "Ich glaube an Gott."),
    ("gratulieren", "zu", "D", "to congratulate on", "Ich gratuliere dir zum Geburtstag."),
    ("halten", "von", "D", "to think of (opinion)", "Was hältst du von dem Vorschlag?"),
    ("sich handeln", "um", "A", "to be a matter of", "Es handelt sich um einen Fehler."),
    ("helfen", "bei", "D", "to help with", "Er hilft mir bei den Hausaufgaben."),
    ("hoffen", "auf", "A", "to hope for", "Wir hoffen auf besseres Wetter."),
    ("hören", "von", "D", "to hear from/about", "Ich habe von dem Unfall gehört."),
    ("sich informieren", "über", "A", "to get information about", "Ich informiere mich über den Kurs."),
    ("sich interessieren", "für", "A", "to be interested in", "Ich interessiere mich für Technik."),
    ("kämpfen", "für", "A", "to fight for", "Sie kämpfen für ihre Rechte."),
    ("kämpfen", "gegen", "A", "to fight against", "Wir kämpfen gegen die Krise."),
    ("sich kümmern", "um", "A", "to take care of", "Ich kümmere mich um das Problem."),
    ("lachen", "über", "A", "to laugh about", "Alle lachen über den Witz."),
    ("leiden", "an", "D", "to suffer from (illness)", "Er leidet an Diabetes."),
    ("leiden", "unter", "D", "to suffer from (conditions)", "Sie leidet unter dem Stress."),
    ("nachdenken", "über", "A", "to think about", "Ich denke über dein Angebot nach."),
    ("passen", "zu", "D", "to match / suit", "Der Schal passt zu deinem Mantel."),
    ("protestieren", "gegen", "A", "to protest against", "Sie protestieren gegen das Gesetz."),
    ("rechnen", "mit", "D", "to count on / expect", "Wir rechnen mit Verspätung."),
    ("reagieren", "auf", "A", "to react to", "Er reagiert schnell auf die Kritik."),
    ("reden", "über", "A", "to talk about", "Wir reden über die Zukunft."),
    ("reden", "mit", "D", "to talk with", "Ich rede mit dem Chef."),
    ("riechen", "nach", "D", "to smell of", "Es riecht nach Rauch."),
    ("schmecken", "nach", "D", "to taste of", "Das schmeckt nach Zitrone."),
    ("schreiben", "an", "A", "to write to", "Ich schreibe an meine Eltern."),
    ("schreiben", "über", "A", "to write about", "Er schreibt über die Umwelt."),
    ("sich schützen", "vor", "D", "to protect oneself from", "Schütze dich vor der Sonne!"),
    ("sich sehnen", "nach", "D", "to long for", "Ich sehne mich nach Ruhe."),
    ("sorgen", "für", "A", "to see to / provide for", "Ich sorge für das Essen."),
    ("sich sorgen", "um", "A", "to worry about", "Sie sorgt sich um ihren Sohn."),
    ("sprechen", "über", "A", "to speak about", "Wir sprechen über das Projekt."),
    ("sprechen", "mit", "D", "to speak with", "Ich spreche mit dem Kunden."),
    ("sterben", "an", "D", "to die of", "Er starb an einem Herzinfarkt."),
    ("streiten", "über", "A", "to argue about", "Sie streiten über Geld."),
    ("streiten", "mit", "D", "to argue with", "Er streitet mit seinem Bruder."),
    ("teilnehmen", "an", "D", "to take part in", "Ich nehme an dem Kurs teil."),
    ("telefonieren", "mit", "D", "to talk on the phone with", "Ich telefoniere mit meiner Mutter."),
    ("träumen", "von", "D", "to dream of", "Ich träume von Deutschland."),
    ("sich treffen", "mit", "D", "to meet with", "Ich treffe mich mit Freunden."),
    ("sich trennen", "von", "D", "to separate from", "Er trennt sich von seiner Firma."),
    ("überreden", "zu", "D", "to persuade to", "Sie überredet ihn zum Mitkommen."),
    ("sich überzeugen", "von", "D", "to convince oneself of", "Überzeugen Sie sich von der Qualität."),
    ("sich unterhalten", "über", "A", "to converse about", "Wir unterhalten uns über Musik."),
    ("sich unterhalten", "mit", "D", "to converse with", "Ich unterhalte mich mit ihr."),
    ("sich verabschieden", "von", "D", "to say goodbye to", "Ich verabschiede mich von euch."),
    ("verfügen", "über", "A", "to have at one's disposal", "Die Firma verfügt über Kapital."),
    ("vergleichen", "mit", "D", "to compare with", "Vergleiche A mit B."),
    ("sich verlassen", "auf", "A", "to rely on", "Ich verlasse mich auf dich."),
    ("sich verlieben", "in", "A", "to fall in love with", "Er verliebt sich in sie."),
    ("verstehen", "unter", "D", "to understand by", "Was verstehst du unter Qualität?"),
    ("sich verstehen", "mit", "D", "to get on with", "Ich verstehe mich gut mit ihm."),
    ("sich vorbereiten", "auf", "A", "to prepare for", "Ich bereite mich auf die Prüfung vor."),
    ("warnen", "vor", "D", "to warn about", "Er warnt vor dem Risiko."),
    ("warten", "auf", "A", "to wait for", "Ich warte auf den Bus."),
    ("sich wenden", "an", "A", "to turn to (person)", "Wenden Sie sich an das Sekretariat."),
    ("werden", "zu", "D", "to turn into", "Das Wasser wird zu Eis."),
    ("wissen", "von", "D", "to know about", "Ich weiß nichts von dem Plan."),
    ("sich wundern", "über", "A", "to be surprised at", "Ich wundere mich über sein Verhalten."),
    ("zählen", "zu", "D", "to be counted among", "Er zählt zu den Besten."),
    ("zweifeln", "an", "D", "to doubt", "Ich zweifle an seiner Aussage."),
    ("zwingen", "zu", "D", "to force to", "Man zwingt ihn zum Verkauf."),
    # ---- B2 / professional and technical register
    ("abraten", "von", "D", "to advise against", "Ich rate dir von dieser Investition ab."),
    ("anpassen", "an", "A", "to adapt to", "Wir passen den Prozess an die Norm an."),
    ("appellieren", "an", "A", "to appeal to", "Er appelliert an die Vernunft."),
    ("aufmerksam machen", "auf", "A", "to draw attention to", "Ich mache Sie auf den Fehler aufmerksam."),
    ("ausgehen", "von", "D", "to assume / start from", "Wir gehen von 20 °C aus."),
    ("basieren", "auf", "D", "to be based on", "Das Modell basiert auf Messdaten."),
    ("sich befassen", "mit", "D", "to deal with", "Die Studie befasst sich mit Katalyse."),
    ("sich belaufen", "auf", "A", "to amount to", "Die Kosten belaufen sich auf 5000 Euro."),
    ("sich beziehen", "auf", "A", "to refer to", "Ich beziehe mich auf Ihr Schreiben."),
    ("bestehen", "in", "D", "to consist in", "Der Vorteil besteht in der Effizienz."),
    ("sich durchsetzen", "gegen", "A", "to prevail against", "Er setzt sich gegen die Konkurrenz durch."),
    ("sich einigen", "auf", "A", "to agree on", "Wir einigen uns auf einen Termin."),
    ("sich einsetzen", "für", "A", "to campaign for", "Sie setzt sich für den Umweltschutz ein."),
    ("sich entwickeln", "zu", "D", "to develop into", "Die Firma entwickelt sich zum Marktführer."),
    ("sich ergeben", "aus", "D", "to result from", "Das ergibt sich aus der Rechnung."),
    ("sich erholen", "von", "D", "to recover from", "Er erholt sich von der Operation."),
    ("sich gliedern", "in", "A", "to be divided into", "Der Bericht gliedert sich in drei Teile."),
    ("hinweisen", "auf", "A", "to point out", "Ich weise auf das Risiko hin."),
    ("sich konzentrieren", "auf", "A", "to concentrate on", "Wir konzentrieren uns auf die Analyse."),
    ("sich lohnen", "für", "A", "to be worth it for", "Die Investition lohnt sich für uns."),
    ("resultieren", "aus", "D", "to result from", "Der Verlust resultiert aus dem Leck."),
    ("sich richten", "an", "A", "to be addressed to", "Der Kurs richtet sich an Ingenieure."),
    ("sich richten", "nach", "D", "to be governed by", "Der Preis richtet sich nach dem Markt."),
    ("schließen", "aus", "D", "to conclude from", "Daraus schließe ich, dass ..."),
    ("sich spezialisieren", "auf", "A", "to specialise in", "Er spezialisiert sich auf Verfahrenstechnik."),
    ("sich stützen", "auf", "A", "to be based on", "Die These stützt sich auf Daten."),
    ("teilen", "in", "A", "to divide into", "Wir teilen die Probe in zwei Teile."),
    ("überzeugen", "von", "D", "to convince of", "Er überzeugt uns von seinem Plan."),
    ("umgehen", "mit", "D", "to handle / deal with", "Man muss vorsichtig mit Säuren umgehen."),
    ("verantwortlich sein", "für", "A", "to be responsible for", "Ich bin für die Anlage verantwortlich."),
    ("verzichten", "auf", "A", "to do without", "Wir verzichten auf Lösungsmittel."),
    ("vorgehen", "gegen", "A", "to take action against", "Die Behörde geht gegen den Betrieb vor."),
    ("sich wehren", "gegen", "A", "to defend oneself against", "Er wehrt sich gegen den Vorwurf."),
    ("sich widmen", "D", "D", "to devote oneself to", "Sie widmet sich der Forschung."),
    ("zurückführen", "auf", "A", "to attribute to", "Man führt den Defekt auf Korrosion zurück."),
    ("zusammenhängen", "mit", "D", "to be connected with", "Das hängt mit dem Druck zusammen."),
    ("zustimmen", "D", "D", "to agree to", "Ich stimme deinem Vorschlag zu."),
]

CASE_LABEL = {"A": "Akkusativ", "D": "Dativ", "-": "—"}

if __name__ == "__main__":
    rows = []
    for verb, prep, case, en, ex in DATA:
        base = verb.replace("sich ", "")
        rows.append({
            "verb": verb, "base": base, "prep": prep,
            "case": CASE_LABEL.get(case, case),
            "pattern": f"{verb} {prep} + {CASE_LABEL.get(case, case)}",
            "en": en, "example": ex,
            "reflexive": "yes" if verb.startswith("sich ") else "no",
        })
    json.dump(rows, open("/tmp/de/verb_prep.json", "w", encoding="utf-8"),
              ensure_ascii=False, indent=1)
    print(f"{len(rows)} verb+preposition patterns, "
          f"{len({r['base'] for r in rows})} distinct verbs")
